### ISSUE TITLE
Annoying printing 

### ISSUE THREAD

**Issue by wialb** [NanBlanc/OSToolBox#1]
Would it be possible to remove the line _print("aaaaaa", field_list)_ please? It's at the line 685 of tools.py.

Thanks!

**Comment by NanBlanc** [comment]
Hi, 
Thank you for your interest in OSToolBox,
I published a newer version correcting that bug.
please do : `pip install --upgrade ostoolbox`

**Comment by wialb** [comment]
Thank you for the update!
Much appreciated
